/**
 * Kong Gateway renderer — custom Lua plugin.
 *
 * The verdict logic is not written by hand here: CHECKS is serialized straight
 * out of VERDICT_RULE, so the Lua and the CLI can never drift.
 *
 * No timestamps or random identifiers are emitted anywhere, so regenerating
 * with the same answers produces byte-identical output and a clean git diff.
 */

import { describeSpec } from '../contract.mjs';

const PLUGIN_NAME = 'tpp-validation';
const PLUGIN_VERSION = '1.0.0';

function luaStr(s) {
  return `"${String(s).replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

function luaPath(path) {
  return `{ ${path.map(luaStr).join(', ')} }`;
}

function luaChecks(rule) {
  return rule
    .map((r) => {
      const parts = [
        `id = ${luaStr(r.id)}`,
        `path = ${luaPath(r.path)}`,
        `op = ${luaStr(r.op)}`,
      ];
      if (r.value !== undefined) parts.push(`value = ${luaStr(r.value)}`);
      parts.push(`reason = ${luaStr(r.reason)}`);
      return `  { ${parts.join(', ')} },`;
    })
    .join('\n');
}

function luaInjectList(headers) {
  return headers.map((h) => `  ${luaStr(h.header)},`).join('\n');
}

function luaInjectMap(headers) {
  return headers
    .map((h) => {
      const read = h.fallbackPath
        ? `dig(data, ${luaPath(h.path)}) or dig(data, ${luaPath(h.fallbackPath)})`
        : `dig(data, ${luaPath(h.path)})`;
      return `      [${luaStr(h.header)}] = ${read},`;
    })
    .join('\n');
}

function luaRoleList(roles) {
  return roles.length ? `{ ${roles.map(luaStr).join(', ')} }` : '{}';
}

function specHeader(spec, comment = '--') {
  const lines = describeSpec(spec).map(([k, v]) => `${comment} ${k.padEnd(20)} ${v}`);
  return [
    `${comment} Generated by tppv integration — do not edit by hand.`,
    `${comment} Regenerate: tppv integration --gateway ${spec.target.id}`,
    comment,
    ...lines,
  ].join('\n');
}

function handlerLua(spec) {
  return `${specHeader(spec)}

local cjson = require "cjson.safe"
local http = require "resty.http"
local sha256 = require "resty.sha256"
local resty_string = require "resty.string"

local kong = kong
local ngx = ngx
local NULL = cjson.null

local PLUGIN_NAME = ${luaStr(PLUGIN_NAME)}
local PLUGIN_VERSION = ${luaStr(PLUGIN_VERSION)}
local RULE_VERSION = ${spec.ruleVersion}

local TppValidation = {
  -- After mtls-auth (1006), so the client certificate is already negotiated.
  -- Before rate-limiting (901) and request-transformer, so traffic that will be
  -- rejected never consumes quota and never reaches a transform.
  PRIORITY = 1005,
  VERSION = PLUGIN_VERSION,
}

-- Serialized from VERDICT_RULE in lib/verdict.mjs. Do not hand-edit: the CLI
-- verdict and this table must stay identical or the gateway and the dashboard
-- will disagree about the same certificate.
local CHECKS = {
${luaChecks(spec.rule)}
}

local OK_FLAGS = { [true] = true, PASSED = true, GOOD = true, granted = true, yes = true, [1] = true }

-- Cleared from every inbound request before we set them. A caller able to send
-- x-tpp-identifier could otherwise impersonate a different TPP to the upstream.
local INJECT_HEADERS = {
${luaInjectList(spec.injectedHeaders)}
}

local FINGERPRINT_HEADER = "x-tpp-fingerprint"

---------------------------------------------------------------------------
-- verdict evaluation
---------------------------------------------------------------------------

local function dig(node, path)
  local cur = node
  for i = 1, #path do
    if type(cur) ~= "table" then return nil end
    cur = cur[path[i]]
    if cur == nil or cur == NULL then return nil end
  end
  return cur
end

-- Days since the Unix epoch, UTC. os.time() would interpret the fields as
-- local time and shift expiry by the container's offset.
local function days_from_civil(y, m, d)
  if m <= 2 then y = y - 1 end
  local era = math.floor(y / 400)
  local yoe = y - era * 400
  local mp = m + (m > 2 and -3 or 9)
  local doy = math.floor((153 * mp + 2) / 5) + d - 1
  local doe = yoe * 365 + math.floor(yoe / 4) - math.floor(yoe / 100) + doy
  return era * 146097 + doe - 719468
end

local function iso_to_epoch(s)
  if type(s) ~= "string" then return nil end
  local y, mo, d, h, mi, sec = string.match(s, "^(%d%d%d%d)-(%d%d)-(%d%d)[T ](%d%d):(%d%d):(%d%d)")
  if not y then
    y, mo, d = string.match(s, "^(%d%d%d%d)-(%d%d)-(%d%d)")
    h, mi, sec = "0", "0", "0"
  end
  if not y then return nil end
  return days_from_civil(tonumber(y), tonumber(mo), tonumber(d)) * 86400
    + tonumber(h) * 3600 + tonumber(mi) * 60 + tonumber(sec)
end

local function test_op(chk, value)
  local op = chk.op

  if op == "okFlag" then
    return OK_FLAGS[value] == true

  elseif op == "equals" then
    return value == chk.value

  elseif op == "truthy" then
    return value ~= nil and value ~= false

  elseif op == "nonEmpty" then
    return type(value) == "string" and #value > 0

  elseif op == "future" then
    if value == nil then return false end
    local epoch = iso_to_epoch(value)
    -- An unparseable notAfter is not treated as expired. /v5 already reports
    -- expiry as certificateRevocation = "EXPIRED", which the revocation check
    -- catches, so denying here as well would turn a date-format change on the
    -- API side into a full outage.
    if not epoch then
      kong.log.warn("unparseable notAfter, expiry check skipped: ", tostring(value))
      return true
    end
    return epoch > ngx.time()

  elseif op == "nonEmptyFirstEntry" then
    return type(value) == "table" and type(value[1]) == "table" and next(value[1]) ~= nil
  end

  kong.log.err("unknown verdict op: ", tostring(op))
  return false
end

local function evaluate(data)
  if type(data) ~= "table" then
    return false, "NoValidationResponse", "response"
  end
  for i = 1, #CHECKS do
    local chk = CHECKS[i]
    if not test_op(chk, dig(data, chk.path)) then
      return false, chk.reason, chk.id
    end
  end
  return true
end

---------------------------------------------------------------------------
-- validator call
---------------------------------------------------------------------------

local function fingerprint(pem)
  local digest = sha256:new()
  digest:update(pem)
  return resty_string.to_hex(digest:final())
end

local function call_validator(conf, pem)
  local httpc = http.new()
  httpc:set_timeout(conf.timeout_ms)

  local url = conf.api_url .. "?cc=" .. ngx.escape_uri(conf.jurisdictions) .. "&details=true"
  local res, err = httpc:request_uri(url, {
    method = "POST",
    body = pem,
    headers = {
      ["Content-Type"] = "text/plain",
      ["Authorization"] = "Bearer " .. conf.bearer_token,
      ["User-Agent"] = "tpp-validation-kong/" .. PLUGIN_VERSION,
    },
    ssl_verify = true,
    keepalive_timeout = 60000,
    keepalive_pool = 8,
  })

  if not res then
    return nil, "validator unreachable: " .. tostring(err)
  end
  if res.status == 401 then
    return nil, "validator rejected the bearer token (401) — check the vault reference"
  end
  -- 200 = validated, 422 = validated and failed. Both carry a usable body;
  -- anything else is an infrastructure problem, not a verdict.
  if res.status ~= 200 and res.status ~= 422 then
    return nil, "validator returned HTTP " .. tostring(res.status)
  end

  local data = cjson.decode(res.body)
  if not data then
    return nil, "validator returned unparseable JSON"
  end
  return data
end

-- mlcache callback. The third return value overrides the entry TTL, which is
-- how deny verdicts get a shorter life than allow verdicts.
local function load_verdict(conf, pem)
  local data, err = call_validator(conf, pem)
  if not data then
    return nil, err
  end

  local allowed, reason, failed_id = evaluate(data)
  local entry = {
    allowed = allowed,
    reason = reason,
    failed = failed_id,
    inject = {
${luaInjectMap(spec.injectedHeaders)}
    },
  }

  local ttl = allowed and conf.cache_ttl_seconds or conf.negative_cache_ttl_seconds
  return entry, nil, ttl
end

---------------------------------------------------------------------------
-- decision
---------------------------------------------------------------------------

local function deny(conf, status, reason, detail)
  -- detail goes to the log, never to the caller: a TPP does not need to know
  -- which internal check tripped or whether our validator was reachable.
  kong.log.warn(PLUGIN_NAME, " denied: ", reason, " — ", tostring(detail))
  return kong.response.exit(status, {
    error = "tpp_validation_failed",
    reason = reason,
  }, {
    ["x-tpp-reason"] = reason,
  })
end

local function role_permitted(allowed, role)
  for candidate in string.gmatch(tostring(role), "[^,%s]+") do
    for i = 1, #allowed do
      if allowed[i] == candidate then return true end
    end
  end
  return false
end

function TppValidation:access(conf)
  for i = 1, #INJECT_HEADERS do
    kong.service.request.clear_header(INJECT_HEADERS[i])
  end
  kong.service.request.clear_header(FINGERPRINT_HEADER)

  local pem, cert_err = kong.client.tls.get_full_client_certificate_chain()
  if not pem then
    return deny(conf, conf.deny_status, "NoClientCertificate",
      "no client certificate on the connection" .. (cert_err and (": " .. cert_err) or "") ..
      " — check nginx_proxy_ssl_verify_client")
  end

  local fp = fingerprint(pem)
  local cache_key = "tppv:r" .. RULE_VERSION .. ":" .. fp .. ":" .. conf.jurisdictions

  local entry, err, hit_level

  if conf.cache_ttl_seconds <= 0 then
    -- mlcache reads ttl = 0 as "never expires", the opposite of caching off,
    -- so bypass the cache entirely rather than passing 0 through.
    entry, err = load_verdict(conf, pem)
  else
    local opts = {
      ttl = conf.cache_ttl_seconds,
      neg_ttl = conf.negative_cache_ttl_seconds,
    }
    if conf.fail_mode == "closed_grace" and conf.grace_ttl_seconds > 0 then
      -- resurrect_ttl serves the stale verdict when the callback errors. This
      -- is the grace window — no bespoke bookkeeping needed.
      opts.resurrect_ttl = conf.grace_ttl_seconds
    end
    entry, err, hit_level = kong.cache:get(cache_key, opts, load_verdict, conf, pem)
  end

  if not entry then
    kong.log.err("validator unavailable: ", tostring(err))
    if conf.fail_mode == "open" then
      kong.log.warn("fail_mode=open — admitting unvalidated certificate ", fp)
      kong.service.request.set_header("x-tpp-validation", "bypassed")
      return
    end
    return deny(conf, conf.unavailable_status, "ValidatorUnavailable", err)
  end

  if err then
    -- Value came back with an error attached: mlcache resurrected a stale
    -- verdict, so we are inside the grace window. Worth an alert, not a deny.
    kong.log.warn("grace window: reusing cached verdict for ", fp,
      " (mlcache hit level ", tostring(hit_level), ") during outage: ", tostring(err))
  end

  if not entry.allowed then
    return deny(conf, conf.deny_status, entry.reason or "ValidationFailed",
      "failed check: " .. tostring(entry.failed))
  end

  if #conf.allowed_roles > 0 then
    local role = entry.inject and entry.inject["x-tpp-roles"]
    if not role or not role_permitted(conf.allowed_roles, role) then
      return deny(conf, conf.deny_status, "RoleNotPermitted",
        "role " .. tostring(role) .. " not permitted on this route")
    end
  end

  if conf.inject_headers then
    for i = 1, #INJECT_HEADERS do
      local header = INJECT_HEADERS[i]
      local value = entry.inject and entry.inject[header]
      if value ~= nil then
        kong.service.request.set_header(header, tostring(value))
      end
    end
    kong.service.request.set_header(FINGERPRINT_HEADER, fp)
  end
end

return TppValidation
`;
}

function schemaLua(spec) {
  return `${specHeader(spec)}

local typedefs = require "kong.db.schema.typedefs"

return {
  name = ${luaStr(PLUGIN_NAME)},
  fields = {
    -- TLS only: without a client certificate the plugin denies every request,
    -- so attaching it to plain http would be a confusing way to break a route.
    { protocols = {
        type = "set",
        required = true,
        default = { "https", "grpcs" },
        elements = { type = "string", one_of = { "https", "grpcs" } },
      },
    },
    { config = {
        type = "record",
        fields = {
          { api_url = typedefs.url { required = true, default = ${luaStr(spec.apiUrl)} } },

          -- referenceable: set this to {vault://env/TPP_BEARER_TOKEN} or any
          -- other Kong vault reference. Never a literal token in kong.yml.
          -- encrypted is honoured on Kong Enterprise and ignored on OSS.
          { bearer_token = {
              type = "string",
              required = true,
              referenceable = true,
              encrypted = true,
            },
          },

          { jurisdictions = { type = "string", required = true, default = ${luaStr(spec.jurisdictions)} } },

          { fail_mode = {
              type = "string",
              required = true,
              default = ${luaStr(spec.failMode)},
              one_of = { "closed", "closed_grace", "open" },
            },
          },

          { cache_ttl_seconds = { type = "integer", default = ${spec.cacheTtl}, between = { 0, 604800 } } },
          { negative_cache_ttl_seconds = { type = "integer", default = ${spec.negativeCacheTtl}, between = { 0, 3600 } } },
          { grace_ttl_seconds = { type = "integer", default = ${spec.graceTtl}, between = { 0, 604800 } } },
          { timeout_ms = { type = "integer", default = ${spec.timeoutMs}, between = { 100, 30000 } } },

          { allowed_roles = {
              type = "array",
              default = ${luaRoleList(spec.allowedRoles)},
              elements = { type = "string", one_of = { "PSP_AI", "PSP_PI", "PSP_IC", "PSP_AS" } },
            },
          },

          { inject_headers = { type = "boolean", default = ${spec.injectHeaders} } },
          { deny_status = { type = "integer", default = ${spec.denyStatus}, between = { 400, 499 } } },
          { unavailable_status = { type = "integer", default = ${spec.unavailableStatus}, between = { 400, 599 } } },
        },
      },
    },
  },
}
`;
}

function declarativeConfig(spec) {
  const roles = spec.allowedRoles.length
    ? `\n          allowed_roles:\n${spec.allowedRoles.map((r) => `            - ${r}`).join('\n')}`
    : '\n          allowed_roles: []';

  return `${specHeader(spec, '#')}

_format_version: "3.0"

services:
  - name: psd2-account-api
    url: http://upstream:80
    routes:
      - name: accounts
        paths:
          - /v1/accounts
        protocols:
          - https

plugins:
  - name: ${PLUGIN_NAME}
    service: psd2-account-api
    config:
      api_url: ${spec.apiUrl}
      # Resolved by Kong at runtime — the literal token never lands in git.
      bearer_token: "{vault://env/TPP_BEARER_TOKEN}"
      jurisdictions: "${spec.jurisdictions}"
      fail_mode: ${spec.failMode}
      cache_ttl_seconds: ${spec.cacheTtl}
      negative_cache_ttl_seconds: ${spec.negativeCacheTtl}
      grace_ttl_seconds: ${spec.graceTtl}
      timeout_ms: ${spec.timeoutMs}${roles}
      inject_headers: ${spec.injectHeaders}
      deny_status: ${spec.denyStatus}
      unavailable_status: ${spec.unavailableStatus}
`;
}

function dockerCompose(spec) {
  return `${specHeader(spec, '#')}
#
# Integration harness. This is the only thing standing between "the Lua looks
# right" and "the Lua works". Run it before you deploy anything.
#
#   export TPP_BEARER_TOKEN=eyJ...
#   docker compose -f docker-compose.test.yml up -d
#   ./test/smoke.sh

services:
  kong:
    image: kong:3.9
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PLUGINS: bundled,${PLUGIN_NAME}
      KONG_LUA_PACKAGE_PATH: /opt/tpp/?.lua;;
      # optional_no_ca hands us the certificate without Kong validating the
      # chain first — trust is delegated to /v5, which is the point.
      KONG_NGINX_PROXY_SSL_VERIFY_CLIENT: optional_no_ca
      KONG_NGINX_PROXY_SSL_VERIFY_DEPTH: "4"
      KONG_PROXY_LISTEN: "0.0.0.0:8000, 0.0.0.0:8443 ssl"
      KONG_LOG_LEVEL: info
      KONG_VAULTS: bundled
      TPP_BEARER_TOKEN: \${TPP_BEARER_TOKEN:?set TPP_BEARER_TOKEN before starting}
    volumes:
      - ./kong.yml:/kong/kong.yml:ro
      - ./kong:/opt/tpp/kong:ro
    ports:
      - "8000:8000"
      - "8443:8443"
    depends_on:
      - upstream

  upstream:
    image: mccutchen/go-httpbin:v2.15.0
    expose:
      - "80"
    environment:
      PORT: "80"
`;
}

function smokeTest(spec) {
  return `#!/usr/bin/env bash
# Smoke test for the generated ${PLUGIN_NAME} plugin.
#
# Expectations:
#   1. no client certificate           -> ${spec.denyStatus} NoClientCertificate
#   2. self-signed non-PSD2 cert       -> ${spec.denyStatus} (first failing check)
#   3. real QWAC                       -> 200, upstream sees x-tpp-* headers
#
# Case 3 needs a certificate that actually validates. Point QWAC at one, or
# leave it unset and case 3 is reported as skipped rather than silently passing.

set -euo pipefail

BASE=\${BASE:-https://localhost:8443}
ROUTE=\${ROUTE:-/v1/accounts}
QWAC=\${QWAC:-}
QWAC_KEY=\${QWAC_KEY:-}

pass() { printf '  \\033[32mok\\033[0m   %s\\n' "$1"; }
fail() { printf '  \\033[31mfail\\033[0m %s\\n' "$1"; exit 1; }
skip() { printf '  \\033[2mskip\\033[0m %s\\n' "$1"; }

echo "1. no client certificate"
code=$(curl -sk -o /dev/null -w '%{http_code}' "$BASE$ROUTE")
[ "$code" = "${spec.denyStatus}" ] && pass "denied with $code" || fail "expected ${spec.denyStatus}, got $code"

echo "2. self-signed certificate"
tmp=$(mktemp -d)
openssl req -x509 -newkey rsa:2048 -nodes -days 1 -subj '/CN=not-a-tpp.example' \\
  -keyout "$tmp/k.pem" -out "$tmp/c.pem" 2>/dev/null
code=$(curl -sk -o /dev/null -w '%{http_code}' --cert "$tmp/c.pem" --key "$tmp/k.pem" "$BASE$ROUTE")
reason=$(curl -sk -D - -o /dev/null --cert "$tmp/c.pem" --key "$tmp/k.pem" "$BASE$ROUTE" \\
  | tr -d '\\r' | awk -F': ' '/^x-tpp-reason/ {print $2}')
rm -rf "$tmp"
[ "$code" = "${spec.denyStatus}" ] && pass "denied with $code (x-tpp-reason: \${reason:-none})" \\
  || fail "expected ${spec.denyStatus}, got $code"

echo "3. valid QWAC"
if [ -z "$QWAC" ] || [ -z "$QWAC_KEY" ]; then
  skip "set QWAC and QWAC_KEY to exercise the allow path"
  exit 0
fi
body=$(curl -sk --cert "$QWAC" --key "$QWAC_KEY" "$BASE$ROUTE/headers")
echo "$body" | grep -qi 'x-tpp-identifier' \\
  && pass "allowed, upstream received x-tpp-* headers" \\
  || fail "allowed but header injection missing: $body"
`;
}

function readme(spec) {
  const table = describeSpec(spec)
    .map(([k, v]) => `| ${k} | ${v} |`)
    .join('\n');

  const graceLine =
    spec.failMode === 'closed_grace'
      ? `Because you chose \`closed_grace\`, a certificate validated within the last ` +
        `${spec.graceTtl}s keeps working through a validator outage. One that has never been ` +
        `seen is denied with ${spec.unavailableStatus}. Alert on the \`grace window\` log line — ` +
        `it means you are running on stale verdicts.`
      : spec.failMode === 'open'
        ? `**You chose \`fail_mode: open\`.** An outage on our side becomes an authorization ` +
          `bypass on yours: requests are admitted with \`x-tpp-validation: bypassed\` and only a ` +
          `log line records it. Alert on that header at the upstream, or reconsider the setting.`
        : `Because you chose \`closed\`, any validator outage denies all TPP traffic with ` +
          `${spec.unavailableStatus}. Nothing stale is ever served. Make sure whoever owns the ` +
          `on-call rotation knows this dependency exists.`;

  const unverified = spec.target.verified
    ? ''
    : `> **Not yet executed.** This plugin was generated against the Kong\n` +
      `> 3.4–3.9 PDK and reviewed, but it has not been run against a live Kong\n` +
      `> instance. \`docker-compose.test.yml\` and \`test/smoke.sh\` in this directory\n` +
      `> exist to change that. Run them before this handles production traffic.\n\n`;

  return `# TPP validation for Kong Gateway

${unverified}Generated by \`tppv integration\`. Regenerate rather than edit:

\`\`\`
tppv integration --gateway kong --out .
\`\`\`

| Setting | Value |
|---|---|
${table}

## What it does

On every request into the protected route, in the \`access\` phase:

1. **extract** — \`kong.client.tls.get_full_client_certificate_chain()\`
2. **decide** — cache lookup on \`${spec.cacheKey}\`, else \`POST ${spec.apiUrl}\`
3. **evaluate** — the ${spec.rule.length} checks in \`CHECKS\`, first failure wins
4. **inject** — ${spec.injectedHeaders.map((h) => `\`${h.header}\``).join(', ')} onto the upstream request
5. **fallback** — \`fail_mode: ${spec.failMode}\`

Inbound \`x-tpp-*\` headers are cleared before injection, so a TPP cannot claim
someone else's identity to your backend.

## Prerequisites

Kong must receive the client certificate. Trust is delegated to \`/v5\`, so Kong
itself does not need to verify the chain:

\`\`\`
# kong.conf — OSS
nginx_proxy_ssl_verify_client = optional_no_ca
nginx_proxy_ssl_verify_depth  = 4
\`\`\`

On Kong Enterprise you can use the \`mtls-auth\` plugin instead; this plugin runs
at priority 1005, immediately after it.

## Install

\`\`\`bash
# 1. put the plugin on Kong's Lua path
cp -r kong /opt/tpp/kong

# 2. kong.conf (or env)
export KONG_LUA_PACKAGE_PATH="/opt/tpp/?.lua;;"
export KONG_PLUGINS="bundled,${PLUGIN_NAME}"

# 3. the bearer token, via a vault reference — never a literal
export TPP_BEARER_TOKEN="eyJ..."

kong reload
\`\`\`

\`bearer_token\` is declared \`referenceable\`, so \`{vault://env/TPP_BEARER_TOKEN}\`
in \`kong.yml\` is resolved at runtime and the token stays out of git and out of
\`/config\` output.

## Test it before you trust it

\`\`\`bash
export TPP_BEARER_TOKEN=eyJ...
docker compose -f docker-compose.test.yml up -d
./test/smoke.sh
\`\`\`

Case 3 (the allow path) is skipped unless you set \`QWAC\` and \`QWAC_KEY\` to a
certificate that actually validates. A green run without case 3 proves only that
the plugin denies things.

## Operational notes

**Outage behaviour.** ${graceLine}

**Revocation lag.** A positive verdict is cached for ${spec.cacheTtl}s, so a
certificate revoked now is still accepted for up to ${spec.cacheTtl}s. That is a
deliberate trade against calling \`/v5\` on every request. Shorten
\`cache_ttl_seconds\` if your risk function wants a tighter window.

**Shared cache.** The plugin uses \`kong.cache\` with a \`tppv:\` key prefix. Above
roughly a thousand distinct certificates per node, give it a dedicated dictionary
instead — add \`nginx_http_lua_shared_dict = tppv 32m\` to \`kong.conf\` and swap the
\`kong.cache:get\` call in \`handler.lua\` for a private \`mlcache\` instance over that
dict, so TPP verdicts stop competing with Kong's own entity cache.

**Rule version.** \`RULE_VERSION = ${spec.ruleVersion}\` is part of the cache key. When
the validation rule changes upstream, the version bumps and deployed gateways
miss cache rather than enforcing yesterday's rule.

**Latency.** Cache hits add well under a millisecond. A miss costs one HTTPS
round trip to \`api.tppvalidation.com\`, bounded by \`timeout_ms: ${spec.timeoutMs}\`.
Only the first request per certificate per ${spec.cacheTtl}s pays it.
`;
}

export function renderKong(spec) {
  return [
    { path: `kong/plugins/${PLUGIN_NAME}/handler.lua`, contents: handlerLua(spec) },
    { path: `kong/plugins/${PLUGIN_NAME}/schema.lua`, contents: schemaLua(spec) },
    { path: 'kong.yml', contents: declarativeConfig(spec) },
    { path: 'docker-compose.test.yml', contents: dockerCompose(spec) },
    { path: 'test/smoke.sh', contents: smokeTest(spec), mode: 0o755 },
    { path: 'README.md', contents: readme(spec) },
  ];
}
